### ISSUE TITLE
Relationship with ciromattia/bootstrap-4-shortcodes Fork

### ISSUE THREAD

**Issue by MikeiLL** [MWDelaney/bootstrap-4-shortcodes#7]
Hey Michael,

I imagine you are familiar with the fork of the BS3 version:

https://github.com/ciromattia/bootstrap-4-shortcodes

Do you think there might be some work there that would be applicable here?

**Comment by MWDelaney** [comment]
Yeah, I've seen that. This plugin does a lot more than the BS3 version did in trying to work with the WordPress editor by inserting classes into actual wrapped links, rather than making you type out the linked URL as a shortcode parameter.

It's different enough that the two aren't really compatible.

I'm glad that the original BS3 version is still seeing some attention, though!
